name: kkiapay_flutter_sdk
description: KkiaPay allows businesses to safely receive payments by mobile money, credit card and bank account.
version: 1.1.0
support: kkiapay <support@kkiapay.me>
homepage: 'https://github.com/kkiapay/kkiapay-flutter-sdk'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

  webview_flutter: ^3.0.4
  cupertino_icons: ^1.0.3
  stacked: ^3.2.0
  stacked_services: ^1.0.0
  logger: ^1.1.0
  socket_io_client: ^1.0.2
  intl:
  retrofit:
  dio:
  built_value:
  json_annotation:
  meta:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  hive_generator:

  stacked_generator:
  retrofit_generator:
  json_serializable:
  built_value_generator:

flutter:
  uses-material-design: true
